<a href="https://colab.research.google.com/github/teemaphorn/delivery-project/blob/main/Project_Parcel_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
#ส่วนรับเข้าพัสดุทีละชิ้น
import random
import pandas as pd

# 1. ประกาศ Class สำหรับเก็บข้อมูลองค์ประกอบต่างๆ

class Customer:
    # เก็บข้อมูลลูกค้า (ผู้ส่ง/ผู้รับ)
    def __init__(self, customer_id, name, phone):
        self.customer_id = customer_id
        self.name = name
        self.phone = phone

class Parcel:
    # เก็บข้อมูลพัสดุและกำหนดประเภทบริการเริ่มต้น
    def __init__(self, parcel_id, weight_kg, service_type="ธรรมดา"):
        self.parcel_id = parcel_id
        self.weight_kg = weight_kg
        self.service_type = service_type

class ParcelIntake:
    # รวมข้อมูลการรับพัสดุ 1 รายการ
    def __init__(self, intake_id, sender_obj, recipient_obj, parcel_obj, distance_km):
        self.intake_id = intake_id
        self.sender = sender_obj
        self.recipient = recipient_obj
        self.parcel = parcel_obj
        self.distance_km = distance_km
        self.status = "รับแล้ว"

    def get_summary(self):
        # แปลงเป็น dict เพื่อเตรียมเอาไปสร้าง DataFrame
        return {
            "intake_id": self.intake_id,
            "parcel_id": self.parcel.parcel_id,
            "sender_name": self.sender.name,
            "recipient_name": self.recipient.name,
            "weight_kg": self.parcel.weight_kg,
            "service_type": self.parcel.service_type,
            "distance_km": self.distance_km,
            "status": self.status
        }


# 2. ฟังก์ชันช่วยสุ่มข้อมูลตัวอย่าง

def generate_customer_name():
    # สุ่มชื่อ-นามสกุล
    first_names = ["เรยา", "มุนินทร์", "มุตตา", "เรณู", "พิไล", "ทองดี"]
    last_names = ["วงศ์เสวต", "จงสวัสดิ์", "จงสวัสดิ์", "ตาคลี", "อัศวรุ่งเรืองกิจ", "บุญพูลทรัพย์ "]
    return f"{random.choice(first_names)} {random.choice(last_names)}"

def generate_random_weight(min_w=0.5, max_w=15.0):
    # สุ่มน้ำหนักพัสดุ (ทศนิยม 2 ตำแหน่ง)
    return round(random.uniform(min_w, max_w), 2)

def generate_random_distance(min_d=1.0, max_d=250.0):
    # สุ่มระยะทาง (ทศนิยม 1 ตำแหน่ง)
    return round(random.uniform(min_d, max_d), 1)


# 3. ส่วนสร้างข้อมูล 300 รายการและบันทึกไฟล์

random.seed(42)  # ล็อกค่า random ให้ผลลัพธ์คงที่
intake_records = []
service_options = ["ธรรมดา", "ด่วนพิเศษ (Express)", "แช่เย็น (Cold Chain)"]

# วนลูปสร้างออเดอร์ 300 รายการ
for i in range(1, 301):
    sender = Customer(f"CUS-S{i:03d}", generate_customer_name(), f"08{random.randint(10000000, 99999999)}")
    recipient = Customer(f"CUS-R{i:03d}", generate_customer_name(), f"09{random.randint(10000000, 99999999)}")

    parcel_item = Parcel(
        parcel_id=f"TH{i:05d}",
        weight_kg=generate_random_weight(),
        service_type=random.choice(service_options)
    )

    intake_item = ParcelIntake(
        intake_id=f"INT-{i:04d}",
        sender_obj=sender,
        recipient_obj=recipient,
        parcel_obj=parcel_item,
        distance_km=generate_random_distance()
    )

    intake_records.append(intake_item.get_summary())

# แปลงเป็น DataFrame และเซฟลง CSV
df_intake = pd.DataFrame(intake_records)
df_intake.to_csv("parcel_intake_300.csv", index=False, encoding="utf-8-sig")

print(f"การรับพัสดุเข้าระบบสำเร็จทั้งหมด: {len(df_intake)} รายการ")
df_intake.head()

การรับพัสดุเข้าระบบสำเร็จทั้งหมด: 300 รายการ

,intake_id,parcel_id,sender_name,recipient_name,weight_kg,service_type,distance_km,status
0,INT-0001,TH00001,ทองดี วงศ์เสวต,ทองดี จงสวัสดิ์,3.74,แช่เย็น (Cold Chain),26.5,รับแล้ว
1,INT-0002,TH00002,ทองดี อัศวรุ่งเรืองกิจ,พิไล ตาคลี,0.93,ธรรมดา,58.9,รับแล้ว
2,INT-0003,TH00003,พิไล วงศ์เสวต,มุนินทร์ บุญพูลทรัพย์,10.67,ด่วนพิเศษ (Express),55.9,รับแล้ว
3,INT-0004,TH00004,พิไล จงสวัสดิ์,มุนินทร์ บุญพูลทรัพย์,5.43,ธรรมดา,54.6,รับแล้ว
4,INT-0005,TH00005,มุตตา วงศ์เสวต,เรณู วงศ์เสวต,12.79,แช่เย็น (Cold Chain),66.9,รับแล้ว

In [14]:
import random
import pandas as pd

def calculate_shipping_fee(weight_kg, distance_km, service_type="ธรรมดา"):
    """
    ฟังก์ชันคำนวณค่าจัดส่งพัสดุ
    - weight_kg: น้ำหนักพัสดุ (กิโลเมตร)
    - distance_km: ระยะทางจัดส่ง (กิโลเมตร)
    - service_type: ประเภทบริการ (มี Default Value เป็น 'ธรรมดา')
    """
    base_fee = 15  # ค่าเปิดบิล(บาท)

# 1. คำนวณค่าบริการตามน้ำหนัก
    if weight_kg <= 1.0:
        weight_fee = 10                         # ไม่เกิน 1 kg คิด 10 บาท
    elif weight_kg <= 5.0:
        weight_fee = 10 + ((weight_kg - 1.0) * 5) # เกิน 1kg คิดเพิ่มkgละ5บาท
    else:
        weight_fee = 30 + ((weight_kg - 5.0) * 8) # เกิน 5 kg คิดเพิ่มkgละ8บาท

# 2. คำนวณค่าระยะทางแบบแบ่งโซน (Zone-based)

    if distance_km <= 15:
        distance_fee = 5
    elif distance_km <= 50:
        distance_fee = 15
    elif distance_km <= 150:
        distance_fee = 30
    else:
        distance_fee = 50

การคำนวณค่าจัดส่งตามน้ำหนัก/ระยะทางทั้งหมด 300 รายการเสร็จสมบูรณ์แล้ว

,intake_id,parcel_id,sender_name,recipient_name,weight_kg,distance_km,service_type,shipping_fee
0,INT-0001,TH00001,ทองดี วงศ์เสวต,ทองดี จงสวัสดิ์,3.74,26.5,แช่เย็น (Cold Chain),53.70
1,INT-0002,TH00002,ทองดี อัศวรุ่งเรืองกิจ,พิไล ตาคลี,0.93,58.9,ธรรมดา,55.00
2,INT-0003,TH00003,พิไล วงศ์เสวต,มุนินทร์ บุญพูลทรัพย์,10.67,55.9,ด่วนพิเศษ (Express),120.36
3,INT-0004,TH00004,พิไล จงสวัสดิ์,มุนินทร์ บุญพูลทรัพย์,5.43,54.6,ธรรมดา,78.44
4,INT-0005,TH00005,มุตตา วงศ์เสวต,เรณู วงศ์เสวต,12.79,66.9,แช่เย็น (Cold Chain),137.32
5,INT-0006,TH00006,เรยา บุญพูลทรัพย์,พิไล วงศ์เสวต,1.64,207.5,ด่วนพิเศษ (Express),78.20
6,INT-0007,TH00007,พิไล จงสวัสดิ์,มุนินทร์ บุญพูลทรัพย์,1.16,193.5,ธรรมดา,75.80
7,INT-0008,TH00008,เรยา จงสวัสดิ์,เรณู จงสวัสดิ์,9.72,41.5,ด่วนพิเศษ (Express),97.76
8,INT-0009,TH00009,มุตตา จงสวัสดิ์,มุตตา บุญพูลทรัพย์,1.54,43.6,แช่เย็น (Cold Chain),42.70
9,INT-0010,TH00010,ทองดี จงสวัสดิ์,เรณู ตาคลี,14.85,172.4,แช่เย็น (Cold Chain),173.80
10,INT-0011,TH00011,มุนินทร์ บุญพูลทรัพย์,เรยา จงสวัสดิ์,12.17,67.7,ด่วนพิเศษ (Express),132.36
11,INT-0012,TH00012,มุนินทร์ อัศวรุ่งเรืองกิจ,มุนินทร์ บุญพูลทรัพย์,6.24,115.3,แช่เย็น (Cold Chain),84.92
12,INT-0013,TH00013,มุตตา จงสวัสดิ์,ทองดี อัศวรุ่งเรืองกิจ,4.31,107.7,แช่เย็น (Cold Chain),71.55
13,INT-0014,TH00014,พิไล ตาคลี,มุนินทร์ จงสวัสดิ์,7.66,215.4,ธรรมดา,116.28
14,INT-0015,TH00015,มุนินทร์ บุญพูลทรัพย์,ทองดี ตาคลี,1.42,149.4,ด่วนพิเศษ (Express),57.10
15,INT-0016,TH00016,เรณู อัศวรุ่งเรืองกิจ,พิไล วงศ์เสวต,10.38,188.0,แช่เย็น (Cold Chain),138.04
16,INT-0017,TH00017,ทองดี จงสวัสดิ์,มุตตา ตาคลี,7.08,219.1,แช่เย็น (Cold Chain),111.64
17,INT-0018,TH00018,มุตตา อัศวรุ่งเรืองกิจ,พิไล วงศ์เสวต,4.83,127.4,แช่เย็น (Cold Chain),74.15
18,INT-0019,TH00019,มุนินทร์ จงสวัสดิ์,มุนินทร์ อัศวรุ่งเรืองกิจ,13.82,81.7,แช่เย็น (Cold Chain),145.56
19,INT-0020,TH00020,เรยา วงศ์เสวต,มุตตา จงสวัสดิ์,3.99,236.8,แช่เย็น (Cold Chain),89.95
20,INT-0021,TH00021,เรยา บุญพูลทรัพย์,เรยา อัศวรุ่งเรืองกิจ,2.36,236.8,ด่วนพิเศษ (Express),81.80
21,INT-0022,TH00022,มุนินทร์ จงสวัสดิ์,พิไล ตาคลี,13.97,172.8,แช่เย็น (Cold Chain),166.76
22,INT-0023,TH00023,ทองดี จงสวัสดิ์,ทองดี บุญพูลทรัพย์,6.85,113.4,แช่เย็น (Cold Chain),89.80
23,INT-0024,TH00024,มุนินทร์ จงสวัสดิ์,มุตตา วงศ์เสวต,8.53,55.8,แช่เย็น (Cold Chain),103.24
24,INT-0025,TH00025,เรยา บุญพูลทรัพย์,เรยา จงสวัสดิ์,13.63,18.6,ด่วนพิเศษ (Express),129.04
25,INT-0026,TH00026,มุนินทร์ จงสวัสดิ์,เรณู จงสวัสดิ์,2.42,144.5,แช่เย็น (Cold Chain),62.10
26,INT-0027,TH00027,มุนินทร์ ตาคลี,มุนินทร์ วงศ์เสวต,10.06,106.5,ด่วนพิเศษ (Express),115.48
27,INT-0028,TH00028,เรณู บุญพูลทรัพย์,ทองดี บุญพูลทรัพย์,1.93,182.3,ด่วนพิเศษ (Express),79.65
28,INT-0029,TH00029,เรยา จงสวัสดิ์,มุนินทร์ อัศวรุ่งเรืองกิจ,2.53,70.4,ธรรมดา,62.65
29,INT-0030,TH00030,มุนินทร์ วงศ์เสวต,พิไล วงศ์เสวต,9.96,209.2,แช่เย็น (Cold Chain),134.68
30,INT-0031,TH00031,เรยา จงสวัสดิ์,เรณู ตาคลี,3.60,225.7,ด่วนพิเศษ (Express),88.00
31,INT-0032,TH00032,มุนินทร์ ตาคลี,เรณู จงสวัสดิ์,4.64,239.4,แช่เย็น (Cold Chain),93.20
32,INT-0033,TH00033,พิไล บุญพูลทรัพย์,มุนินทร์ จงสวัสดิ์,3.66,145.2,ธรรมดา,68.30
33,INT-0034,TH00034,พิไล วงศ์เสวต,เรยา วงศ์เสวต,7.41,40.2,แช่เย็น (Cold Chain),79.28
34,INT-0035,TH00035,พิไล วงศ์เสวต,เรยา อัศวรุ่งเรืองกิจ,10.29,101.5,ธรรมดา,117.32
35,INT-0036,TH00036,พิไล จงสวัสดิ์,พิไล วงศ์เสวต,1.69,146.3,แช่เย็น (Cold Chain),58.45
36,INT-0037,TH00037,พิไล จงสวัสดิ์,มุนินทร์ บุญพูลทรัพย์,3.96,33.6,ด่วนพิเศษ (Express),54.80
37,INT-0038,TH00038,ทองดี จงสวัสดิ์,มุตตา วงศ์เสวต,7.15,249.0,แช่เย็น (Cold Chain),112.20
38,INT-0039,TH00039,เรยา อัศวรุ่งเรืองกิจ,พิไล จงสวัสดิ์,14.03,219.9,ธรรมดา,167.24
39,INT-0040,TH00040,มุตตา จงสวัสดิ์,เรณู อัศวรุ่งเรืองกิจ,9.37,132.7,แช่เย็น (Cold Chain),109.96
40,INT-0041,TH00041,ทองดี อัศวรุ่งเรืองกิจ,ทองดี วงศ์เสวต,4.33,185.9,ธรรมดา,91.65
41,INT-0042,TH00042,มุนินทร์ จงสวัสดิ์,พิไล จงสวัสดิ์,3.45,213.4,แช่เย็น (Cold Chain),87.25
42,INT-0043,TH00043,พิไล ตาคลี,เรยา วงศ์เสวต,6.64,12.0,ด่วนพิเศษ (Express),63.12
43,INT-0044,TH00044,มุตตา จงสวัสดิ์,มุตตา จงสวัสดิ์,8.50,140.7,ด่วนพิเศษ (Express),103.00
44,INT-0045,TH00045,เรยา วงศ์เสวต,พิไล วงศ์เสวต,8.95,108.0,ธรรมดา,106.60
45,INT-0046,TH00046,เรยา จงสวัสดิ์,เรยา จงสวัสดิ์,10.39,26.6,แช่เย็น (Cold Chain),103.12
46,INT-0047,TH00047,พิไล ตาคลี,ทองดี จงสวัสดิ์,13.04,220.5,ธรรมดา,159.32
47,INT-0048,TH00048,เรยา จงสวัสดิ์,เรณู บุญพูลทรัพย์,4.37,27.9,แช่เย็น (Cold Chain),56.85
48,INT-0049,TH00049,เรยา ตาคลี,มุนินทร์ ตาคลี,4.93,56.5,ธรรมดา,74.65
49,INT-0050,TH00050,ทองดี จงสวัสดิ์,มุตตา จงสวัสดิ์,14.52,88.4,ด่วนพิเศษ (Express),151.16
50,INT-0051,TH00051,พิไล ตาคลี,มุตตา วงศ์เสวต,13.22,45.5,ด่วนพิเศษ (Express),125.76
51,INT-0052,TH00052,มุตตา วงศ์เสวต,พิไล ตาคลี,11.06,109.7,ด่วนพิเศษ (Express),123.48
52,INT-0053,TH00053,พิไล วงศ์เสวต,พิไล จงสวัสดิ์,1.14,1.4,ด่วนพิเศษ (Express),30.70
53,INT-0054,TH00054,พิไล บุญพูลทรัพย์,มุตตา ตาคลี,14.26,156.2,ด่วนพิเศษ (Express),169.08
54,INT-0055,TH00055,ทองดี วงศ์เสวต,พิไล จงสวัสดิ์,6.42,174.6,ด่วนพิเศษ (Express),106.36
55,INT-0056,TH00056,พิไล จงสวัสดิ์,เรณู บุญพูลทรัพย์,10.32,154.3,ธรรมดา,137.56
56,INT-0057,TH00057,มุตตา ตาคลี,เรยา จงสวัสดิ์,3.55,152.1,แช่เย็น (Cold Chain),87.75
57,INT-0058,TH00058,มุตตา ตาคลี,เรณู บุญพูลทรัพย์,7.91,43.3,แช่เย็น (Cold Chain),83.28
58,INT-0059,TH00059,เรยา จงสวัสดิ์,ทองดี บุญพูลทรัพย์,5.36,168.5,ธรรมดา,97.88
59,INT-0060,TH00060,มุนินทร์ จงสวัสดิ์,เรยา วงศ์เสวต,14.77,212.6,แช่เย็น (Cold Chain),173.16
60,INT-0061,TH00061,เรยา ตาคลี,ทองดี อัศวรุ่งเรืองกิจ,10.92,124.1,ด่วนพิเศษ (Express),122.36
61,INT-0062,TH00062,มุนินทร์ จงสวัสดิ์,ทองดี วงศ์เสวต,11.79,44.8,ธรรมดา,114.32
62,INT-0063,TH00063,ทองดี อัศวรุ่งเรืองกิจ,เรยา อัศวรุ่งเรืองกิจ,13.80,114.7,ธรรมดา,145.40
63,INT-0064,TH00064,เรณู บุญพูลทรัพย์,พิไล อัศวรุ่งเรืองกิจ,14.28,153.6,ด่วนพิเศษ (Express),169.24
64,INT-0065,TH00065,ทองดี อัศวรุ่งเรืองกิจ,พิไล ตาคลี,11.28,113.1,ด่วนพิเศษ (Express),125.24
65,INT-0066,TH00066,มุนินทร์ บุญพูลทรัพย์,พิไล ตาคลี,3.97,20.3,ด่วนพิเศษ (Express),54.85
66,INT-0067,TH00067,มุตตา จงสวัสดิ์,มุตตา จงสวัสดิ์,1.67,58.6,ธรรมดา,58.35
67,INT-0068,TH00068,ทองดี จงสวัสดิ์,เรยา ตาคลี,5.30,104.5,ด่วนพิเศษ (Express),77.40
68,INT-0069,TH00069,มุนินทร์ ตาคลี,พิไล บุญพูลทรัพย์,12.92,95.7,แช่เย็น (Cold Chain),138.36
69,INT-0070,TH00070,เรยา จงสวัสดิ์,เรณู ตาคลี,11.34,200.2,แช่เย็น (Cold Chain),145.72
70,INT-0071,TH00071,มุนินทร์ ตาคลี,มุตตา ตาคลี,0.92,167.5,ด่วนพิเศษ (Express),75.00
71,INT-0072,TH00072,เรณู บุญพูลทรัพย์,เรณู จงสวัสดิ์,8.24,148.4,ด่วนพิเศษ (Express),100.92
72,INT-0073,TH00073,ทองดี วงศ์เสวต,ทองดี ตาคลี,13.07,13.5,ธรรมดา,114.56
73,INT-0074,TH00074,เรณู จงสวัสดิ์,เรณู จงสวัสดิ์,11.54,70.3,ด่วนพิเศษ (Express),127.32
74,INT-0075,TH00075,เรณู จงสวัสดิ์,เรณู วงศ์เสวต,1.26,56.8,ด่วนพิเศษ (Express),56.30
75,INT-0076,TH00076,เรยา บุญพูลทรัพย์,เรยา จงสวัสดิ์,12.67,38.9,แช่เย็น (Cold Chain),121.36
76,INT-0077,TH00077,มุนินทร์ ตาคลี,เรยา อัศวรุ่งเรืองกิจ,7.24,192.0,ด่วนพิเศษ (Express),112.92
77,INT-0078,TH00078,มุนินทร์ อัศวรุ่งเรืองกิจ,ทองดี บุญพูลทรัพย์,11.78,241.2,ธรรมดา,149.24
78,INT-0079,TH00079,เรยา อัศวรุ่งเรืองกิจ,มุตตา อัศวรุ่งเรืองกิจ,6.25,50.4,แช่เย็น (Cold Chain),85.00
79,INT-0080,TH00080,พิไล บุญพูลทรัพย์,มุนินทร์ วงศ์เสวต,12.83,201.6,แช่เย็น (Cold Chain),157.64
80,INT-0081,TH00081,พิไล วงศ์เสวต,พิไล ตาคลี,5.87,162.2,แช่เย็น (Cold Chain),101.96
81,INT-0082,TH00082,เรยา ตาคลี,เรยา ตาคลี,9.72,177.1,ด่วนพิเศษ (Express),132.76
82,INT-0083,TH00083,เรณู จงสวัสดิ์,ทองดี จงสวัสดิ์,12.22,193.9,แช่เย็น (Cold Chain),152.76
83,INT-0084,TH00084,เรณู ตาคลี,มุตตา จงสวัสดิ์,12.55,70.5,ธรรมดา,135.40
84,INT-0085,TH00085,เรณู จงสวัสดิ์,พิไล อัศวรุ่งเรืองกิจ,6.00,124.1,ธรรมดา,83.00
85,INT-0086,TH00086,มุตตา จงสวัสดิ์,มุนินทร์ จงสวัสดิ์,5.43,175.6,แช่เย็น (Cold Chain),98.44
86,INT-0087,TH00087,มุตตา อัศวรุ่งเรืองกิจ,พิไล จงสวัสดิ์,4.00,122.7,ด่วนพิเศษ (Express),70.00
87,INT-0088,TH00088,มุนินทร์ บุญพูลทรัพย์,ทองดี บุญพูลทรัพย์,7.00,24.2,ธรรมดา,76.00
88,INT-0089,TH00089,มุนินทร์ ตาคลี,มุตตา บุญพูลทรัพย์,5.85,133.2,แช่เย็น (Cold Chain),81.80
89,INT-0090,TH00090,เรณู บุญพูลทรัพย์,มุตตา จงสวัสดิ์,4.43,58.4,ด่วนพิเศษ (Express),72.15
90,INT-0091,TH00091,ทองดี จงสวัสดิ์,เรยา บุญพูลทรัพย์,14.29,47.1,แช่เย็น (Cold Chain),134.32
91,INT-0092,TH00092,มุนินทร์ บุญพูลทรัพย์,มุตตา บุญพูลทรัพย์,14.66,149.6,แช่เย็น (Cold Chain),152.28
92,INT-0093,TH00093,เรยา จงสวัสดิ์,มุนินทร์ จงสวัสดิ์,4.88,134.0,แช่เย็น (Cold Chain),74.40
93,INT-0094,TH00094,มุตตา วงศ์เสวต,พิไล จงสวัสดิ์,9.75,26.5,ด่วนพิเศษ (Express),98.00
94,INT-0095,TH00095,เรยา อัศวรุ่งเรืองกิจ,เรณู ตาคลี,5.44,63.9,ธรรมดา,78.52
95,INT-0096,TH00096,เรณู วงศ์เสวต,เรณู ตาคลี,8.87,14.3,แช่เย็น (Cold Chain),80.96
96,INT-0097,TH00097,มุนินทร์ อัศวรุ่งเรืองกิจ,เรยา จงสวัสดิ์,8.59,152.0,ด่วนพิเศษ (Express),123.72
97,INT-0098,TH00098,พิไล จงสวัสดิ์,เรณู ตาคลี,4.81,247.5,แช่เย็น (Cold Chain),94.05
98,INT-0099,TH00099,มุตตา อัศวรุ่งเรืองกิจ,เรยา อัศวรุ่งเรืองกิจ,14.24,156.8,ธรรมดา,168.92
99,INT-0100,TH00100,มุตตา บุญพูลทรัพย์,มุนินทร์ จงสวัสดิ์,8.50,1.7,ธรรมดา,78.00
100,INT-0101,TH00101,เรณู บุญพูลทรัพย์,เรณู จงสวัสดิ์,3.86,71.4,แช่เย็น (Cold Chain),69.30
101,INT-0102,TH00102,เรณู วงศ์เสวต,มุตตา บุญพูลทรัพย์,10.09,106.9,ธรรมดา,115.72
102,INT-0103,TH00103,พิไล จงสวัสดิ์,มุนินทร์ จงสวัสดิ์,1.54,198.4,ธรรมดา,77.70
103,INT-0104,TH00104,พิไล บุญพูลทรัพย์,มุตตา ตาคลี,7.30,175.2,ด่วนพิเศษ (Express),113.40
104,INT-0105,TH00105,มุตตา อัศวรุ่งเรืองกิจ,เรณู ตาคลี,9.17,183.9,ด่วนพิเศษ (Express),128.36
105,INT-0106,TH00106,พิไล จงสวัสดิ์,เรยา จงสวัสดิ์,9.01,249.9,ธรรมดา,127.08
106,INT-0107,TH00107,ทองดี จงสวัสดิ์,เรยา จงสวัสดิ์,8.02,229.1,ด่วนพิเศษ (Express),119.16
107,INT-0108,TH00108,มุนินทร์ อัศวรุ่งเรืองกิจ,ทองดี ตาคลี,7.32,84.0,ด่วนพิเศษ (Express),93.56
108,INT-0109,TH00109,ทองดี วงศ์เสวต,มุตตา ตาคลี,4.68,203.6,ด่วนพิเศษ (Express),93.40
109,INT-0110,TH00110,พิไล วงศ์เสวต,เรยา จงสวัสดิ์,5.19,216.4,ด่วนพิเศษ (Express),96.52
110,INT-0111,TH00111,เรยา บุญพูลทรัพย์,เรณู ตาคลี,3.22,156.0,ด่วนพิเศษ (Express),86.10
111,INT-0112,TH00112,เรณู บุญพูลทรัพย์,เรยา จงสวัสดิ์,8.46,110.1,ด่วนพิเศษ (Express),102.68
112,INT-0113,TH00113,ทองดี ตาคลี,เรยา บุญพูลทรัพย์,12.09,40.4,แช่เย็น (Cold Chain),116.72
113,INT-0114,TH00114,พิไล วงศ์เสวต,เรณู วงศ์เสวต,14.89,115.9,ธรรมดา,154.12
114,INT-0115,TH00115,เรยา บุญพูลทรัพย์,เรณู บุญพูลทรัพย์,7.88,104.5,ด่วนพิเศษ (Express),98.04
115,INT-0116,TH00116,เรณู ตาคลี,เรณู อัศวรุ่งเรืองกิจ,6.06,127.6,แช่เย็น (Cold Chain),83.48
116,INT-0117,TH00117,มุนินทร์ วงศ์เสวต,เรณู จงสวัสดิ์,4.37,71.4,ธรรมดา,71.85
117,INT-0118,TH00118,มุตตา อัศวรุ่งเรืองกิจ,ทองดี ตาคลี,6.97,86.9,ด่วนพิเศษ (Express),90.76
118,INT-0119,TH00119,พิไล อัศวรุ่งเรืองกิจ,เรณู จงสวัสดิ์,14.72,143.4,ธรรมดา,152.76
119,INT-0120,TH00120,มุนินทร์ ตาคลี,มุตตา บุญพูลทรัพย์,10.73,97.1,ด่วนพิเศษ (Express),120.84
120,INT-0121,TH00121,ทองดี บุญพูลทรัพย์,เรณู วงศ์เสวต,7.78,83.7,แช่เย็น (Cold Chain),97.24
121,INT-0122,TH00122,เรยา ตาคลี,พิไล ตาคลี,10.98,217.9,ด่วนพิเศษ (Express),142.84
122,INT-0123,TH00123,มุนินทร์ วงศ์เสวต,มุตตา จงสวัสดิ์,10.54,21.0,แช่เย็น (Cold Chain),104.32
123,INT-0124,TH00124,มุตตา บุญพูลทรัพย์,เรณู จงสวัสดิ์,10.92,218.2,ด่วนพิเศษ (Express),142.36
124,INT-0125,TH00125,เรยา อัศวรุ่งเรืองกิจ,มุนินทร์ บุญพูลทรัพย์,14.96,23.5,แช่เย็น (Cold Chain),139.68
125,INT-0126,TH00126,เรยา บุญพูลทรัพย์,เรณู จงสวัสดิ์,13.60,81.8,ธรรมดา,143.80
126,INT-0127,TH00127,เรยา จงสวัสดิ์,มุตตา ตาคลี,4.04,141.9,ด่วนพิเศษ (Express),70.20
127,INT-0128,TH00128,มุนินทร์ จงสวัสดิ์,เรยา อัศวรุ่งเรืองกิจ,9.49,124.9,ธรรมดา,110.92
128,INT-0129,TH00129,พิไล จงสวัสดิ์,เรณู บุญพูลทรัพย์,7.16,3.3,แช่เย็น (Cold Chain),67.28
129,INT-0130,TH00130,เรณู จงสวัสดิ์,มุนินทร์ วงศ์เสวต,14.21,75.5,แช่เย็น (Cold Chain),148.68
130,INT-0131,TH00131,เรณู บุญพูลทรัพย์,เรณู จงสวัสดิ์,14.99,27.6,ด่วนพิเศษ (Express),139.92
131,INT-0132,TH00132,เรณู อัศวรุ่งเรืองกิจ,พิไล จงสวัสดิ์,0.82,99.6,แช่เย็น (Cold Chain),55.00
132,INT-0133,TH00133,เรยา อัศวรุ่งเรืองกิจ,พิไล บุญพูลทรัพย์,12.58,194.2,ด่วนพิเศษ (Express),155.64
133,INT-0134,TH00134,มุนินทร์ อัศวรุ่งเรืองกิจ,มุนินทร์ บุญพูลทรัพย์,9.50,189.1,แช่เย็น (Cold Chain),131.00
134,INT-0135,TH00135,ทองดี บุญพูลทรัพย์,ทองดี วงศ์เสวต,9.87,197.4,ด่วนพิเศษ (Express),133.96
135,INT-0136,TH00136,เรยา อัศวรุ่งเรืองกิจ,ทองดี จงสวัสดิ์,13.69,187.1,ด่วนพิเศษ (Express),164.52
136,INT-0137,TH00137,มุนินทร์ จงสวัสดิ์,พิไล จงสวัสดิ์,7.78,207.8,ด่วนพิเศษ (Express),117.24
137,INT-0138,TH00138,มุตตา ตาคลี,ทองดี จงสวัสดิ์,7.29,36.0,ธรรมดา,78.32
138,INT-0139,TH00139,มุนินทร์ บุญพูลทรัพย์,พิไล จงสวัสดิ์,11.96,66.9,ธรรมดา,130.68
139,INT-0140,TH00140,เรยา ตาคลี,ทองดี บุญพูลทรัพย์,8.98,235.1,แช่เย็น (Cold Chain),126.84
140,INT-0141,TH00141,เรยา บุญพูลทรัพย์,เรณู วงศ์เสวต,13.32,82.7,แช่เย็น (Cold Chain),141.56
141,INT-0142,TH00142,พิไล จงสวัสดิ์,เรยา บุญพูลทรัพย์,13.69,162.7,ด่วนพิเศษ (Express),164.52
142,INT-0143,TH00143,เรยา จงสวัสดิ์,เรยา จงสวัสดิ์,2.18,221.9,ธรรมดา,80.90
143,INT-0144,TH00144,มุนินทร์ ตาคลี,มุตตา บุญพูลทรัพย์,6.58,181.9,แช่เย็น (Cold Chain),107.64
144,INT-0145,TH00145,เรณู บุญพูลทรัพย์,เรณู อัศวรุ่งเรืองกิจ,14.12,9.1,ด่วนพิเศษ (Express),122.96
145,INT-0146,TH00146,มุตตา จงสวัสดิ์,เรณู จงสวัสดิ์,1.94,92.5,แช่เย็น (Cold Chain),59.70
146,INT-0147,TH00147,ทองดี จงสวัสดิ์,เรณู จงสวัสดิ์,14.54,23.8,ด่วนพิเศษ (Express),136.32
147,INT-0148,TH00148,มุนินทร์ บุญพูลทรัพย์,พิไล วงศ์เสวต,11.91,247.2,ธรรมดา,150.28
148,INT-0149,TH00149,พิไล จงสวัสดิ์,พิไล จงสวัสดิ์,3.63,82.8,ธรรมดา,68.15
149,INT-0150,TH00150,มุนินทร์ อัศวรุ่งเรืองกิจ,มุตตา จงสวัสดิ์,8.33,28.4,ธรรมดา,86.64
150,INT-0151,TH00151,เรยา จงสวัสดิ์,มุตตา จงสวัสดิ์,5.19,67.1,ธรรมดา,76.52
151,INT-0152,TH00152,มุนินทร์ บุญพูลทรัพย์,พิไล วงศ์เสวต,7.41,128.8,ด่วนพิเศษ (Express),94.28
152,INT-0153,TH00153,เรยา ตาคลี,มุนินทร์ อัศวรุ่งเรืองกิจ,11.05,130.8,แช่เย็น (Cold Chain),123.40
153,INT-0154,TH00154,เรณู บุญพูลทรัพย์,เรยา ตาคลี,6.68,123.1,ธรรมดา,88.44
154,INT-0155,TH00155,เรณู วงศ์เสวต,มุตตา อัศวรุ่งเรืองกิจ,1.45,156.5,ด่วนพิเศษ (Express),77.25
155,INT-0156,TH00156,พิไล อัศวรุ่งเรืองกิจ,เรณู อัศวรุ่งเรืองกิจ,4.78,151.8,แช่เย็น (Cold Chain),93.90
156,INT-0157,TH00157,เรยา บุญพูลทรัพย์,ทองดี บุญพูลทรัพย์,10.95,108.1,ธรรมดา,122.60
157,INT-0158,TH00158,มุนินทร์ ตาคลี,เรณู ตาคลี,11.08,107.3,ด่วนพิเศษ (Express),123.64
158,INT-0159,TH00159,ทองดี จงสวัสดิ์,มุนินทร์ บุญพูลทรัพย์,1.47,24.2,ธรรมดา,42.35
159,INT-0160,TH00160,เรยา บุญพูลทรัพย์,มุนินทร์ อัศวรุ่งเรืองกิจ,9.00,140.9,แช่เย็น (Cold Chain),107.00
160,INT-0161,TH00161,ทองดี วงศ์เสวต,มุตตา บุญพูลทรัพย์,13.09,13.8,แช่เย็น (Cold Chain),114.72
161,INT-0162,TH00162,มุตตา อัศวรุ่งเรืองกิจ,มุตตา วงศ์เสวต,7.86,164.5,ธรรมดา,117.88
162,INT-0163,TH00163,มุนินทร์ วงศ์เสวต,พิไล จงสวัสดิ์,11.56,57.3,แช่เย็น (Cold Chain),127.48
163,INT-0164,TH00164,เรณู อัศวรุ่งเรืองกิจ,พิไล บุญพูลทรัพย์,8.57,232.3,แช่เย็น (Cold Chain),123.56
164,INT-0165,TH00165,ทองดี จงสวัสดิ์,มุนินทร์ จงสวัสดิ์,13.86,2.5,ด่วนพิเศษ (Express),120.88
165,INT-0166,TH00166,มุนินทร์ อัศวรุ่งเรืองกิจ,เรณู วงศ์เสวต,11.24,23.8,ธรรมดา,109.92
166,INT-0167,TH00167,พิไล จงสวัสดิ์,เรณู ตาคลี,2.78,180.7,ด่วนพิเศษ (Express),83.90
167,INT-0168,TH00168,พิไล อัศวรุ่งเรืองกิจ,เรยา จงสวัสดิ์,11.44,168.8,ธรรมดา,146.52
168,INT-0169,TH00169,มุตตา ตาคลี,เรณู ตาคลี,6.91,54.7,ด่วนพิเศษ (Express),90.28
169,INT-0170,TH00170,พิไล วงศ์เสวต,เรณู วงศ์เสวต,10.33,122.2,แช่เย็น (Cold Chain),117.64
170,INT-0171,TH00171,ทองดี จงสวัสดิ์,มุนินทร์ ตาคลี,1.29,76.1,ธรรมดา,56.45
171,INT-0172,TH00172,มุนินทร์ จงสวัสดิ์,มุตตา จงสวัสดิ์,0.61,108.2,แช่เย็น (Cold Chain),55.00
172,INT-0173,TH00173,มุนินทร์ ตาคลี,ทองดี จงสวัสดิ์,8.60,201.7,แช่เย็น (Cold Chain),123.80
173,INT-0174,TH00174,เรยา ตาคลี,เรณู วงศ์เสวต,13.86,144.4,ด่วนพิเศษ (Express),145.88
174,INT-0175,TH00175,พิไล ตาคลี,เรณู จงสวัสดิ์,6.37,43.8,ด่วนพิเศษ (Express),70.96
175,INT-0176,TH00176,พิไล ตาคลี,เรยา ตาคลี,4.03,100.7,แช่เย็น (Cold Chain),70.15
176,INT-0177,TH00177,เรยา ตาคลี,ทองดี จงสวัสดิ์,5.33,20.0,ธรรมดา,62.64
177,INT-0178,TH00178,ทองดี วงศ์เสวต,พิไล จงสวัสดิ์,5.59,203.9,แช่เย็น (Cold Chain),99.72
178,INT-0179,TH00179,มุนินทร์ วงศ์เสวต,มุตตา จงสวัสดิ์,9.23,19.8,แช่เย็น (Cold Chain),93.84
179,INT-0180,TH00180,ทองดี ตาคลี,พิไล อัศวรุ่งเรืองกิจ,10.38,161.1,แช่เย็น (Cold Chain),138.04
180,INT-0181,TH00181,พิไล จงสวัสดิ์,มุตตา จงสวัสดิ์,1.49,158.2,ด่วนพิเศษ (Express),77.45
181,INT-0182,TH00182,มุตตา อัศวรุ่งเรืองกิจ,มุตตา อัศวรุ่งเรืองกิจ,5.00,10.4,ด่วนพิเศษ (Express),50.00
182,INT-0183,TH00183,มุตตา จงสวัสดิ์,ทองดี วงศ์เสวต,9.11,116.2,ด่วนพิเศษ (Express),107.88
183,INT-0184,TH00184,พิไล บุญพูลทรัพย์,เรณู อัศวรุ่งเรืองกิจ,3.23,119.4,แช่เย็น (Cold Chain),66.15
184,INT-0185,TH00185,มุนินทร์ วงศ์เสวต,เรยา จงสวัสดิ์,7.82,10.7,ธรรมดา,72.56
185,INT-0186,TH00186,ทองดี ตาคลี,พิไล อัศวรุ่งเรืองกิจ,2.80,229.6,ด่วนพิเศษ (Express),84.00
186,INT-0187,TH00187,เรณู ตาคลี,ทองดี อัศวรุ่งเรืองกิจ,11.94,84.3,แช่เย็น (Cold Chain),130.52
187,INT-0188,TH00188,มุตตา วงศ์เสวต,ทองดี ตาคลี,4.15,241.1,แช่เย็น (Cold Chain),90.75
188,INT-0189,TH00189,พิไล จงสวัสดิ์,เรยา อัศวรุ่งเรืองกิจ,2.55,78.2,ด่วนพิเศษ (Express),62.75
189,INT-0190,TH00190,ทองดี บุญพูลทรัพย์,เรณู จงสวัสดิ์,10.78,78.1,ธรรมดา,121.24
190,INT-0191,TH00191,เรณู บุญพูลทรัพย์,มุนินทร์ บุญพูลทรัพย์,1.86,106.4,แช่เย็น (Cold Chain),59.30
191,INT-0192,TH00192,มุตตา วงศ์เสวต,มุตตา จงสวัสดิ์,5.46,48.8,ด่วนพิเศษ (Express),63.68
192,INT-0193,TH00193,มุนินทร์ จงสวัสดิ์,มุตตา วงศ์เสวต,11.68,221.0,แช่เย็น (Cold Chain),148.44
193,INT-0194,TH00194,เรยา บุญพูลทรัพย์,พิไล จงสวัสดิ์,5.96,46.0,ธรรมดา,67.68
194,INT-0195,TH00195,ทองดี อัศวรุ่งเรืองกิจ,ทองดี ตาคลี,6.46,180.2,แช่เย็น (Cold Chain),106.68
195,INT-0196,TH00196,เรณู อัศวรุ่งเรืองกิจ,ทองดี ตาคลี,8.24,241.4,ด่วนพิเศษ (Express),120.92
196,INT-0197,TH00197,เรณู จงสวัสดิ์,ทองดี อัศวรุ่งเรืองกิจ,7.19,194.8,ด่วนพิเศษ (Express),112.52
197,INT-0198,TH00198,พิไล อัศวรุ่งเรืองกิจ,มุนินทร์ จงสวัสดิ์,2.51,14.0,ด่วนพิเศษ (Express),37.55
198,INT-0199,TH00199,เรณู จงสวัสดิ์,เรยา บุญพูลทรัพย์,12.84,21.9,ด่วนพิเศษ (Express),122.72
199,INT-0200,TH00200,มุนินทร์ จงสวัสดิ์,พิไล จงสวัสดิ์,1.83,204.4,ธรรมดา,79.15
200,INT-0201,TH00201,มุตตา วงศ์เสวต,เรยา ตาคลี,5.92,248.6,ด่วนพิเศษ (Express),102.36
201,INT-0202,TH00202,มุตตา จงสวัสดิ์,มุตตา วงศ์เสวต,5.36,35.3,ธรรมดา,62.88
202,INT-0203,TH00203,มุตตา ตาคลี,ทองดี ตาคลี,9.42,5.7,ธรรมดา,85.36
203,INT-0204,TH00204,มุนินทร์ จงสวัสดิ์,ทองดี อัศวรุ่งเรืองกิจ,6.64,60.2,ด่วนพิเศษ (Express),88.12
204,INT-0205,TH00205,เรยา วงศ์เสวต,เรณู บุญพูลทรัพย์,7.13,209.3,ธรรมดา,112.04
205,INT-0206,TH00206,เรณู อัศวรุ่งเรืองกิจ,เรยา บุญพูลทรัพย์,8.84,36.8,แช่เย็น (Cold Chain),90.72
206,INT-0207,TH00207,เรณู วงศ์เสวต,มุตตา จงสวัสดิ์,6.54,167.4,แช่เย็น (Cold Chain),107.32
207,INT-0208,TH00208,พิไล จงสวัสดิ์,พิไล อัศวรุ่งเรืองกิจ,11.90,139.0,แช่เย็น (Cold Chain),130.20
208,INT-0209,TH00209,เรณู ตาคลี,ทองดี ตาคลี,4.18,89.9,ธรรมดา,70.90
209,INT-0210,TH00210,เรยา จงสวัสดิ์,ทองดี บุญพูลทรัพย์,2.00,184.1,แช่เย็น (Cold Chain),80.00
210,INT-0211,TH00211,มุตตา จงสวัสดิ์,มุตตา อัศวรุ่งเรืองกิจ,12.30,207.8,ธรรมดา,153.40
211,INT-0212,TH00212,ทองดี ตาคลี,ทองดี จงสวัสดิ์,1.41,10.2,ด่วนพิเศษ (Express),32.05
212,INT-0213,TH00213,มุนินทร์ วงศ์เสวต,เรยา จงสวัสดิ์,7.97,118.9,แช่เย็น (Cold Chain),98.76
213,INT-0214,TH00214,เรยา บุญพูลทรัพย์,มุตตา จงสวัสดิ์,13.05,69.0,ด่วนพิเศษ (Express),139.40
214,INT-0215,TH00215,มุตตา ตาคลี,ทองดี ตาคลี,5.42,124.6,ธรรมดา,78.36
215,INT-0216,TH00216,เรณู จงสวัสดิ์,มุตตา วงศ์เสวต,1.64,248.8,แช่เย็น (Cold Chain),78.20
216,INT-0217,TH00217,มุนินทร์ อัศวรุ่งเรืองกิจ,มุตตา วงศ์เสวต,5.25,77.3,ด่วนพิเศษ (Express),77.00
217,INT-0218,TH00218,พิไล บุญพูลทรัพย์,มุนินทร์ บุญพูลทรัพย์,5.60,182.0,ธรรมดา,99.80
218,INT-0219,TH00219,มุตตา อัศวรุ่งเรืองกิจ,มุตตา บุญพูลทรัพย์,1.59,102.1,แช่เย็น (Cold Chain),57.95
219,INT-0220,TH00220,พิไล บุญพูลทรัพย์,เรยา จงสวัสดิ์,10.33,9.7,ด่วนพิเศษ (Express),92.64
220,INT-0221,TH00221,เรยา จงสวัสดิ์,มุตตา จงสวัสดิ์,14.27,151.7,ธรรมดา,169.16
221,INT-0222,TH00222,ทองดี ตาคลี,มุตตา ตาคลี,8.82,92.4,แช่เย็น (Cold Chain),105.56
222,INT-0223,TH00223,มุตตา บุญพูลทรัพย์,มุนินทร์ วงศ์เสวต,11.17,129.9,ด่วนพิเศษ (Express),124.36
223,INT-0224,TH00224,พิไล วงศ์เสวต,มุตตา บุญพูลทรัพย์,3.61,72.1,แช่เย็น (Cold Chain),68.05
224,INT-0225,TH00225,เรณู จงสวัสดิ์,มุนินทร์ วงศ์เสวต,3.00,111.8,แช่เย็น (Cold Chain),65.00

In [12]:
import random
import pandas as pd


# 1. ประกาศ Class ParcelStatusTracker ก่อนใช้งาน
class ParcelStatusTracker:

    def __init__(self, intake_id, parcel_id, recipient_name, old_status):
        self.intake_id = intake_id
        self.parcel_id = parcel_id
        self.recipient_name = recipient_name
        self.old_status = old_status
        self.new_status = old_status

    def update_status(self, target_status):
        valid_statuses = ["รับแล้ว", "กำลังส่ง", "ส่งสำเร็จ"]
        if target_status in valid_statuses:
            self.new_status = target_status


# ---  วนลูปสุ่มอัปเดตสถานะใหม่ ---
status_options = ["รับแล้ว", "กำลังส่ง", "ส่งสำเร็จ"]
updated_statuses = []

for idx, row in df_intake.iterrows():
    tracker = ParcelStatusTracker(
        intake_id=row["intake_id"],
        parcel_id=row["parcel_id"],
        recipient_name=row["recipient_name"],
        old_status=row["status"],
    )

    next_status = random.choice(status_options)
    tracker.update_status(next_status)
    updated_statuses.append(tracker.new_status)

# สร้าง df_result และเพิ่มคอลัมน์สถานะ
df_result = df_intake.copy()
df_result["old_status"] = df_result["status"]
df_result["updated_status"] = updated_statuses

# กำหนดการจัดเรียงคอลัมน์
columns_order = [
    "intake_id",
    "parcel_id",
    "sender_name",
    "recipient_name",
    "weight_kg",
    "service_type",
    "distance_km",
    "old_status",
    "updated_status",
]

df_result = df_result[columns_order]

# บันทึกไฟล์ CSV
df_result.to_csv("parcel_tracked_300.csv", index=False, encoding="utf-8-sig")

print(f"การรับพัสดุและอัปเดตสถานะสำเร็จทั้งหมด: {len(df_result)} รายการ")
df_result

การรับพัสดุและอัปเดตสถานะสำเร็จทั้งหมด: 300 รายการ

,intake_id,parcel_id,sender_name,recipient_name,weight_kg,service_type,distance_km,old_status,updated_status
0,INT-0001,TH00001,ทองดี วงศ์เสวต,ทองดี จงสวัสดิ์,3.74,แช่เย็น (Cold Chain),26.5,รับแล้ว,ส่งสำเร็จ
1,INT-0002,TH00002,ทองดี อัศวรุ่งเรืองกิจ,พิไล ตาคลี,0.93,ธรรมดา,58.9,รับแล้ว,ส่งสำเร็จ
2,INT-0003,TH00003,พิไล วงศ์เสวต,มุนินทร์ บุญพูลทรัพย์,10.67,ด่วนพิเศษ (Express),55.9,รับแล้ว,กำลังส่ง
3,INT-0004,TH00004,พิไล จงสวัสดิ์,มุนินทร์ บุญพูลทรัพย์,5.43,ธรรมดา,54.6,รับแล้ว,กำลังส่ง
4,INT-0005,TH00005,มุตตา วงศ์เสวต,เรณู วงศ์เสวต,12.79,แช่เย็น (Cold Chain),66.9,รับแล้ว,กำลังส่ง
...,...,...,...,...,...,...,...,...,...
295,INT-0296,TH00296,เรณู อัศวรุ่งเรืองกิจ,มุนินทร์ ตาคลี,4.20,ด่วนพิเศษ (Express),162.0,รับแล้ว,กำลังส่ง
296,INT-0297,TH00297,เรณู จงสวัสดิ์,พิไล บุญพูลทรัพย์,1.25,ด่วนพิเศษ (Express),168.7,รับแล้ว,ส่งสำเร็จ
297,INT-0298,TH00298,พิไล วงศ์เสวต,มุนินทร์ อัศวรุ่งเรืองกิจ,3.65,ธรรมดา,217.5,รับแล้ว,ส่งสำเร็จ
298,INT-0299,TH00299,มุตตา จงสวัสดิ์,มุนินทร์ จงสวัสดิ์,11.33,ด่วนพิเศษ (Express),228.7,รับแล้ว,รับแล้ว
299,INT-0300,TH00300,ทองดี อัศวรุ่งเรืองกิจ,เรณู จงสวัสดิ์,5.16,ด่วนพิเศษ (Express),95.8,รับแล้ว,กำลังส่ง